const PROCESS = process.env

export const ENV = {
  PORT: PROCESS.PORT as string,
  CORS_ALLOW: PROCESS.PORT as string,
  API_URL_HARRY_POTTER: PROCESS.API_URL_HARRY_POTTER as string,
  API_URL_RICK_AND_MORTY: PROCESS.API_URL_RICK_AND_MORTY as string,
  IMAGE_HARRY_POTTER_PLACEHOLDER: PROCESS.IMAGE_HARRY_POTTER_PLACEHOLDER as string
}
