/// <reference types="react" />
/// <reference types="react" />
export declare const FooterElement: import("styled-components").IStyledComponent<"web", {
    ref?: import("react").LegacyRef<HTMLElement>;
    key?: import("react").Key;
    defaultChecked?: boolean;
    defaultValue?: string | number | readonly string[];
    suppressContentEditableWarning?: boolean;
    suppressHydrationWarning?: boolean;
    accessKey?: string;
    autoFocus?: boolean;
    className?: string;
    contentEditable?: "inherit" | (boolean | "false" | "true");
    contextMenu?: string;
    dir?: string;
    draggable?: boolean | "false" | "true";
    hidden?: boolean;
    id?: string;
    lang?: string;
    nonce?: string;
    placeholder?: string;
    slot?: string;
    spellCheck?: boolean | "false" | "true";
    style?: import("react").CSSProperties;
    tabIndex?: number;
    title?: string;
    translate?: "yes" | "no";
    radioGroup?: string;
    role?: import("react").AriaRole;
    about?: string;
    content?: string;
    datatype?: string;
    inlist?: any;
    prefix?: string;
    property?: string;
    rel?: string;
    resource?: string;
    rev?: string;
    typeof?: string;
    vocab?: string;
    autoCapitalize?: string;
    autoCorrect?: string;
    autoSave?: string;
    color?: string;
    itemProp?: string;
    itemScope?: boolean;
    itemType?: string;
    itemID?: string;
    itemRef?: string;
    results?: number;
    security?: string;
    unselectable?: "on" | "off";
    inputMode?: "search" | "numeric" | "none" | "url" | "text" | "decimal" | "tel" | "email";
    is?: string;
    "aria-activedescendant"?: string;
    "aria-atomic"?: boolean | "false" | "true";
    "aria-autocomplete"?: "inline" | "both" | "none" | "list";
    "aria-busy"?: boolean | "false" | "true";
    "aria-checked"?: boolean | "false" | "mixed" | "true";
    "aria-colcount"?: number;
    "aria-colindex"?: number;
    "aria-colspan"?: number;
    "aria-controls"?: string;
    "aria-current"?: boolean | "location" | "time" | "false" | "page" | "true" | "step" | "date";
    "aria-describedby"?: string;
    "aria-details"?: string;
    "aria-disabled"?: boolean | "false" | "true";
    "aria-dropeffect"?: "link" | "none" | "copy" | "move" | "execute" | "popup";
    "aria-errormessage"?: string;
    "aria-expanded"?: boolean | "false" | "true";
    "aria-flowto"?: string;
    "aria-grabbed"?: boolean | "false" | "true";
    "aria-haspopup"?: boolean | "grid" | "dialog" | "menu" | "false" | "listbox" | "true" | "tree";
    "aria-hidden"?: boolean | "false" | "true";
    "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling";
    "aria-keyshortcuts"?: string;
    "aria-label"?: string;
    "aria-labelledby"?: string;
    "aria-level"?: number;
    "aria-live"?: "off" | "assertive" | "polite";
    "aria-modal"?: boolean | "false" | "true";
    "aria-multiline"?: boolean | "false" | "true";
    "aria-multiselectable"?: boolean | "false" | "true";
    "aria-orientation"?: "horizontal" | "vertical";
    "aria-owns"?: string;
    "aria-placeholder"?: string;
    "aria-posinset"?: number;
    "aria-pressed"?: boolean | "false" | "mixed" | "true";
    "aria-readonly"?: boolean | "false" | "true";
    "aria-relevant"?: "all" | "text" | "additions" | "additions removals" | "additions text" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals";
    "aria-required"?: boolean | "false" | "true";
    "aria-roledescription"?: string;
    "aria-rowcount"?: number;
    "aria-rowindex"?: number;
    "aria-rowspan"?: number;
    "aria-selected"?: boolean | "false" | "true";
    "aria-setsize"?: number;
    "aria-sort"?: "none" | "other" | "ascending" | "descending";
    "aria-valuemax"?: number;
    "aria-valuemin"?: number;
    "aria-valuenow"?: number;
    "aria-valuetext"?: string;
    children?: import("react").ReactNode;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    };
    onCopy?: import("react").ClipboardEventHandler<HTMLElement>;
    onCopyCapture?: import("react").ClipboardEventHandler<HTMLElement>;
    onCut?: import("react").ClipboardEventHandler<HTMLElement>;
    onCutCapture?: import("react").ClipboardEventHandler<HTMLElement>;
    onPaste?: import("react").ClipboardEventHandler<HTMLElement>;
    onPasteCapture?: import("react").ClipboardEventHandler<HTMLElement>;
    onCompositionEnd?: import("react").CompositionEventHandler<HTMLElement>;
    onCompositionEndCapture?: import("react").CompositionEventHandler<HTMLElement>;
    onCompositionStart?: import("react").CompositionEventHandler<HTMLElement>;
    onCompositionStartCapture?: import("react").CompositionEventHandler<HTMLElement>;
    onCompositionUpdate?: import("react").CompositionEventHandler<HTMLElement>;
    onCompositionUpdateCapture?: import("react").CompositionEventHandler<HTMLElement>;
    onFocus?: import("react").FocusEventHandler<HTMLElement>;
    onFocusCapture?: import("react").FocusEventHandler<HTMLElement>;
    onBlur?: import("react").FocusEventHandler<HTMLElement>;
    onBlurCapture?: import("react").FocusEventHandler<HTMLElement>;
    onChange?: import("react").FormEventHandler<HTMLElement>;
    onChangeCapture?: import("react").FormEventHandler<HTMLElement>;
    onBeforeInput?: import("react").FormEventHandler<HTMLElement>;
    onBeforeInputCapture?: import("react").FormEventHandler<HTMLElement>;
    onInput?: import("react").FormEventHandler<HTMLElement>;
    onInputCapture?: import("react").FormEventHandler<HTMLElement>;
    onReset?: import("react").FormEventHandler<HTMLElement>;
    onResetCapture?: import("react").FormEventHandler<HTMLElement>;
    onSubmit?: import("react").FormEventHandler<HTMLElement>;
    onSubmitCapture?: import("react").FormEventHandler<HTMLElement>;
    onInvalid?: import("react").FormEventHandler<HTMLElement>;
    onInvalidCapture?: import("react").FormEventHandler<HTMLElement>;
    onLoad?: import("react").ReactEventHandler<HTMLElement>;
    onLoadCapture?: import("react").ReactEventHandler<HTMLElement>;
    onError?: import("react").ReactEventHandler<HTMLElement>;
    onErrorCapture?: import("react").ReactEventHandler<HTMLElement>;
    onKeyDown?: import("react").KeyboardEventHandler<HTMLElement>;
    onKeyDownCapture?: import("react").KeyboardEventHandler<HTMLElement>;
    onKeyPress?: import("react").KeyboardEventHandler<HTMLElement>;
    onKeyPressCapture?: import("react").KeyboardEventHandler<HTMLElement>;
    onKeyUp?: import("react").KeyboardEventHandler<HTMLElement>;
    onKeyUpCapture?: import("react").KeyboardEventHandler<HTMLElement>;
    onAbort?: import("react").ReactEventHandler<HTMLElement>;
    onAbortCapture?: import("react").ReactEventHandler<HTMLElement>;
    onCanPlay?: import("react").ReactEventHandler<HTMLElement>;
    onCanPlayCapture?: import("react").ReactEventHandler<HTMLElement>;
    onCanPlayThrough?: import("react").ReactEventHandler<HTMLElement>;
    onCanPlayThroughCapture?: import("react").ReactEventHandler<HTMLElement>;
    onDurationChange?: import("react").ReactEventHandler<HTMLElement>;
    onDurationChangeCapture?: import("react").ReactEventHandler<HTMLElement>;
    onEmptied?: import("react").ReactEventHandler<HTMLElement>;
    onEmptiedCapture?: import("react").ReactEventHandler<HTMLElement>;
    onEncrypted?: import("react").ReactEventHandler<HTMLElement>;
    onEncryptedCapture?: import("react").ReactEventHandler<HTMLElement>;
    onEnded?: import("react").ReactEventHandler<HTMLElement>;
    onEndedCapture?: import("react").ReactEventHandler<HTMLElement>;
    onLoadedData?: import("react").ReactEventHandler<HTMLElement>;
    onLoadedDataCapture?: import("react").ReactEventHandler<HTMLElement>;
    onLoadedMetadata?: import("react").ReactEventHandler<HTMLElement>;
    onLoadedMetadataCapture?: import("react").ReactEventHandler<HTMLElement>;
    onLoadStart?: import("react").ReactEventHandler<HTMLElement>;
    onLoadStartCapture?: import("react").ReactEventHandler<HTMLElement>;
    onPause?: import("react").ReactEventHandler<HTMLElement>;
    onPauseCapture?: import("react").ReactEventHandler<HTMLElement>;
    onPlay?: import("react").ReactEventHandler<HTMLElement>;
    onPlayCapture?: import("react").ReactEventHandler<HTMLElement>;
    onPlaying?: import("react").ReactEventHandler<HTMLElement>;
    onPlayingCapture?: import("react").ReactEventHandler<HTMLElement>;
    onProgress?: import("react").ReactEventHandler<HTMLElement>;
    onProgressCapture?: import("react").ReactEventHandler<HTMLElement>;
    onRateChange?: import("react").ReactEventHandler<HTMLElement>;
    onRateChangeCapture?: import("react").ReactEventHandler<HTMLElement>;
    onSeeked?: import("react").ReactEventHandler<HTMLElement>;
    onSeekedCapture?: import("react").ReactEventHandler<HTMLElement>;
    onSeeking?: import("react").ReactEventHandler<HTMLElement>;
    onSeekingCapture?: import("react").ReactEventHandler<HTMLElement>;
    onStalled?: import("react").ReactEventHandler<HTMLElement>;
    onStalledCapture?: import("react").ReactEventHandler<HTMLElement>;
    onSuspend?: import("react").ReactEventHandler<HTMLElement>;
    onSuspendCapture?: import("react").ReactEventHandler<HTMLElement>;
    onTimeUpdate?: import("react").ReactEventHandler<HTMLElement>;
    onTimeUpdateCapture?: import("react").ReactEventHandler<HTMLElement>;
    onVolumeChange?: import("react").ReactEventHandler<HTMLElement>;
    onVolumeChangeCapture?: import("react").ReactEventHandler<HTMLElement>;
    onWaiting?: import("react").ReactEventHandler<HTMLElement>;
    onWaitingCapture?: import("react").ReactEventHandler<HTMLElement>;
    onAuxClick?: import("react").MouseEventHandler<HTMLElement>;
    onAuxClickCapture?: import("react").MouseEventHandler<HTMLElement>;
    onClick?: import("react").MouseEventHandler<HTMLElement>;
    onClickCapture?: import("react").MouseEventHandler<HTMLElement>;
    onContextMenu?: import("react").MouseEventHandler<HTMLElement>;
    onContextMenuCapture?: import("react").MouseEventHandler<HTMLElement>;
    onDoubleClick?: import("react").MouseEventHandler<HTMLElement>;
    onDoubleClickCapture?: import("react").MouseEventHandler<HTMLElement>;
    onDrag?: import("react").DragEventHandler<HTMLElement>;
    onDragCapture?: import("react").DragEventHandler<HTMLElement>;
    onDragEnd?: import("react").DragEventHandler<HTMLElement>;
    onDragEndCapture?: import("react").DragEventHandler<HTMLElement>;
    onDragEnter?: import("react").DragEventHandler<HTMLElement>;
    onDragEnterCapture?: import("react").DragEventHandler<HTMLElement>;
    onDragExit?: import("react").DragEventHandler<HTMLElement>;
    onDragExitCapture?: import("react").DragEventHandler<HTMLElement>;
    onDragLeave?: import("react").DragEventHandler<HTMLElement>;
    onDragLeaveCapture?: import("react").DragEventHandler<HTMLElement>;
    onDragOver?: import("react").DragEventHandler<HTMLElement>;
    onDragOverCapture?: import("react").DragEventHandler<HTMLElement>;
    onDragStart?: import("react").DragEventHandler<HTMLElement>;
    onDragStartCapture?: import("react").DragEventHandler<HTMLElement>;
    onDrop?: import("react").DragEventHandler<HTMLElement>;
    onDropCapture?: import("react").DragEventHandler<HTMLElement>;
    onMouseDown?: import("react").MouseEventHandler<HTMLElement>;
    onMouseDownCapture?: import("react").MouseEventHandler<HTMLElement>;
    onMouseEnter?: import("react").MouseEventHandler<HTMLElement>;
    onMouseLeave?: import("react").MouseEventHandler<HTMLElement>;
    onMouseMove?: import("react").MouseEventHandler<HTMLElement>;
    onMouseMoveCapture?: import("react").MouseEventHandler<HTMLElement>;
    onMouseOut?: import("react").MouseEventHandler<HTMLElement>;
    onMouseOutCapture?: import("react").MouseEventHandler<HTMLElement>;
    onMouseOver?: import("react").MouseEventHandler<HTMLElement>;
    onMouseOverCapture?: import("react").MouseEventHandler<HTMLElement>;
    onMouseUp?: import("react").MouseEventHandler<HTMLElement>;
    onMouseUpCapture?: import("react").MouseEventHandler<HTMLElement>;
    onSelect?: import("react").ReactEventHandler<HTMLElement>;
    onSelectCapture?: import("react").ReactEventHandler<HTMLElement>;
    onTouchCancel?: import("react").TouchEventHandler<HTMLElement>;
    onTouchCancelCapture?: import("react").TouchEventHandler<HTMLElement>;
    onTouchEnd?: import("react").TouchEventHandler<HTMLElement>;
    onTouchEndCapture?: import("react").TouchEventHandler<HTMLElement>;
    onTouchMove?: import("react").TouchEventHandler<HTMLElement>;
    onTouchMoveCapture?: import("react").TouchEventHandler<HTMLElement>;
    onTouchStart?: import("react").TouchEventHandler<HTMLElement>;
    onTouchStartCapture?: import("react").TouchEventHandler<HTMLElement>;
    onPointerDown?: import("react").PointerEventHandler<HTMLElement>;
    onPointerDownCapture?: import("react").PointerEventHandler<HTMLElement>;
    onPointerMove?: import("react").PointerEventHandler<HTMLElement>;
    onPointerMoveCapture?: import("react").PointerEventHandler<HTMLElement>;
    onPointerUp?: import("react").PointerEventHandler<HTMLElement>;
    onPointerUpCapture?: import("react").PointerEventHandler<HTMLElement>;
    onPointerCancel?: import("react").PointerEventHandler<HTMLElement>;
    onPointerCancelCapture?: import("react").PointerEventHandler<HTMLElement>;
    onPointerEnter?: import("react").PointerEventHandler<HTMLElement>;
    onPointerEnterCapture?: import("react").PointerEventHandler<HTMLElement>;
    onPointerLeave?: import("react").PointerEventHandler<HTMLElement>;
    onPointerLeaveCapture?: import("react").PointerEventHandler<HTMLElement>;
    onPointerOver?: import("react").PointerEventHandler<HTMLElement>;
    onPointerOverCapture?: import("react").PointerEventHandler<HTMLElement>;
    onPointerOut?: import("react").PointerEventHandler<HTMLElement>;
    onPointerOutCapture?: import("react").PointerEventHandler<HTMLElement>;
    onGotPointerCapture?: import("react").PointerEventHandler<HTMLElement>;
    onGotPointerCaptureCapture?: import("react").PointerEventHandler<HTMLElement>;
    onLostPointerCapture?: import("react").PointerEventHandler<HTMLElement>;
    onLostPointerCaptureCapture?: import("react").PointerEventHandler<HTMLElement>;
    onScroll?: import("react").UIEventHandler<HTMLElement>;
    onScrollCapture?: import("react").UIEventHandler<HTMLElement>;
    onWheel?: import("react").WheelEventHandler<HTMLElement>;
    onWheelCapture?: import("react").WheelEventHandler<HTMLElement>;
    onAnimationStart?: import("react").AnimationEventHandler<HTMLElement>;
    onAnimationStartCapture?: import("react").AnimationEventHandler<HTMLElement>;
    onAnimationEnd?: import("react").AnimationEventHandler<HTMLElement>;
    onAnimationEndCapture?: import("react").AnimationEventHandler<HTMLElement>;
    onAnimationIteration?: import("react").AnimationEventHandler<HTMLElement>;
    onAnimationIterationCapture?: import("react").AnimationEventHandler<HTMLElement>;
    onTransitionEnd?: import("react").TransitionEventHandler<HTMLElement>;
    onTransitionEndCapture?: import("react").TransitionEventHandler<HTMLElement>;
}>;
